# Install Alpine Linux:

docker pull arm64v8/alpine

# Create a bridge:

docker network create --driver bridge hw03

# Create an alpine linux-based mosquitto container:

docker run --name mosquitto --network hw03 -p 1883:1883 -ti arm64v8/alpine sh

# Install mosquitto:

apk update && apk add mosquitto

# Run mosquitto:

/usr/sbin/mosquitto